### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by saniko** [mmellado/mellados.com#1]
https://mellados-com.herokuapp.com/
Link is broken.

FYI

**Comment by mmellado** [comment]
I am aware. Server broke after updating the version of react but haven't
had the time to roll back and fix the issue. Thanks for the flag!

**Comment by mmellado** [comment]
I have reverted the version of react and react-dom to ^0.14.1, which turns out to be 0.14.8. This has fixed the site so it should be accessible now via the url in the README
